package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * AdqDet generated by hbm2java
 */
public class AdqDet  implements java.io.Serializable {


     private AdqDetId id;
     private Integer adqCant;

    public AdqDet() {
    }

	
    public AdqDet(AdqDetId id) {
        this.id = id;
    }
    public AdqDet(AdqDetId id, Integer adqCant) {
       this.id = id;
       this.adqCant = adqCant;
    }
   
    public AdqDetId getId() {
        return this.id;
    }
    
    public void setId(AdqDetId id) {
        this.id = id;
    }
    public Integer getAdqCant() {
        return this.adqCant;
    }
    
    public void setAdqCant(Integer adqCant) {
        this.adqCant = adqCant;
    }




}


