package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * AdqDetId generated by hbm2java
 */
public class AdqDetId  implements java.io.Serializable {


     private int adqCod;
     private int artCod;

    public AdqDetId() {
    }

    public AdqDetId(int adqCod, int artCod) {
       this.adqCod = adqCod;
       this.artCod = artCod;
    }
   
    public int getAdqCod() {
        return this.adqCod;
    }
    
    public void setAdqCod(int adqCod) {
        this.adqCod = adqCod;
    }
    public int getArtCod() {
        return this.artCod;
    }
    
    public void setArtCod(int artCod) {
        this.artCod = artCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdqDetId) ) return false;
		 AdqDetId castOther = ( AdqDetId ) other; 
         
		 return (this.getAdqCod()==castOther.getAdqCod())
 && (this.getArtCod()==castOther.getArtCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdqCod();
         result = 37 * result + this.getArtCod();
         return result;
   }   


}


