package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Adquisicion generated by hbm2java
 */
public class Adquisicion  implements java.io.Serializable {


     private Integer adqCod;
     private Date adqFec;
     private Date adqCarg;
     private String tpAdq;
     private int proCod;
     private Character adqEstado;

    public Adquisicion() {
    }

	
    public Adquisicion(int proCod) {
        this.proCod = proCod;
    }
    public Adquisicion(Date adqFec, Date adqCarg, String tpAdq, int proCod, Character adqEstado) {
       this.adqFec = adqFec;
       this.adqCarg = adqCarg;
       this.tpAdq = tpAdq;
       this.proCod = proCod;
       this.adqEstado = adqEstado;
    }
   
    public Integer getAdqCod() {
        return this.adqCod;
    }
    
    public void setAdqCod(Integer adqCod) {
        this.adqCod = adqCod;
    }
    public Date getAdqFec() {
        return this.adqFec;
    }
    
    public void setAdqFec(Date adqFec) {
        this.adqFec = adqFec;
    }
    public Date getAdqCarg() {
        return this.adqCarg;
    }
    
    public void setAdqCarg(Date adqCarg) {
        this.adqCarg = adqCarg;
    }
    public String getTpAdq() {
        return this.tpAdq;
    }
    
    public void setTpAdq(String tpAdq) {
        this.tpAdq = tpAdq;
    }
    public int getProCod() {
        return this.proCod;
    }
    
    public void setProCod(int proCod) {
        this.proCod = proCod;
    }
    public Character getAdqEstado() {
        return this.adqEstado;
    }
    
    public void setAdqEstado(Character adqEstado) {
        this.adqEstado = adqEstado;
    }




}


