package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * AjustesId generated by hbm2java
 */
public class AjustesId  implements java.io.Serializable {


     private int ajuCod;
     private int artCod;

    public AjustesId() {
    }

    public AjustesId(int ajuCod, int artCod) {
       this.ajuCod = ajuCod;
       this.artCod = artCod;
    }
   
    public int getAjuCod() {
        return this.ajuCod;
    }
    
    public void setAjuCod(int ajuCod) {
        this.ajuCod = ajuCod;
    }
    public int getArtCod() {
        return this.artCod;
    }
    
    public void setArtCod(int artCod) {
        this.artCod = artCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AjustesId) ) return false;
		 AjustesId castOther = ( AjustesId ) other; 
         
		 return (this.getAjuCod()==castOther.getAjuCod())
 && (this.getArtCod()==castOther.getArtCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAjuCod();
         result = 37 * result + this.getArtCod();
         return result;
   }   


}


