package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Barrio generated by hbm2java
 */
public class Barrio  implements java.io.Serializable {


     private Integer barCod;
     private String descripcion;

    public Barrio() {
    }

    public Barrio(String descripcion) {
       this.descripcion = descripcion;
    }
   
    public Integer getBarCod() {
        return this.barCod;
    }
    
    public void setBarCod(Integer barCod) {
        this.barCod = barCod;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


