package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Beca generated by hbm2java
 */
public class Beca  implements java.io.Serializable {


     private Integer becCod;
     private Date fechaCarga;
     private Character becEstado;
     private int perCod;
     private int benCod;
     private Boolean becAprobado;

    public Beca() {
    }

	
    public Beca(int perCod, int benCod) {
        this.perCod = perCod;
        this.benCod = benCod;
    }
    public Beca(Date fechaCarga, Character becEstado, int perCod, int benCod, Boolean becAprobado) {
       this.fechaCarga = fechaCarga;
       this.becEstado = becEstado;
       this.perCod = perCod;
       this.benCod = benCod;
       this.becAprobado = becAprobado;
    }
   
    public Integer getBecCod() {
        return this.becCod;
    }
    
    public void setBecCod(Integer becCod) {
        this.becCod = becCod;
    }
    public Date getFechaCarga() {
        return this.fechaCarga;
    }
    
    public void setFechaCarga(Date fechaCarga) {
        this.fechaCarga = fechaCarga;
    }
    public Character getBecEstado() {
        return this.becEstado;
    }
    
    public void setBecEstado(Character becEstado) {
        this.becEstado = becEstado;
    }
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }
    public int getBenCod() {
        return this.benCod;
    }
    
    public void setBenCod(int benCod) {
        this.benCod = benCod;
    }
    public Boolean getBecAprobado() {
        return this.becAprobado;
    }
    
    public void setBecAprobado(Boolean becAprobado) {
        this.becAprobado = becAprobado;
    }




}


