package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Caja generated by hbm2java
 */
public class Caja  implements java.io.Serializable {


     private Integer cajCod;
     private String cajDesc;

    public Caja() {
    }

    public Caja(String cajDesc) {
       this.cajDesc = cajDesc;
    }
   
    public Integer getCajCod() {
        return this.cajCod;
    }
    
    public void setCajCod(Integer cajCod) {
        this.cajCod = cajCod;
    }
    public String getCajDesc() {
        return this.cajDesc;
    }
    
    public void setCajDesc(String cajDesc) {
        this.cajDesc = cajDesc;
    }




}


