package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * CalDetId generated by hbm2java
 */
public class CalDetId  implements java.io.Serializable {


     private int calCod;
     private int plaMat;
     private int matCod;

    public CalDetId() {
    }

    public CalDetId(int calCod, int plaMat, int matCod) {
       this.calCod = calCod;
       this.plaMat = plaMat;
       this.matCod = matCod;
    }
   
    public int getCalCod() {
        return this.calCod;
    }
    
    public void setCalCod(int calCod) {
        this.calCod = calCod;
    }
    public int getPlaMat() {
        return this.plaMat;
    }
    
    public void setPlaMat(int plaMat) {
        this.plaMat = plaMat;
    }
    public int getMatCod() {
        return this.matCod;
    }
    
    public void setMatCod(int matCod) {
        this.matCod = matCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalDetId) ) return false;
		 CalDetId castOther = ( CalDetId ) other; 
         
		 return (this.getCalCod()==castOther.getCalCod())
 && (this.getPlaMat()==castOther.getPlaMat())
 && (this.getMatCod()==castOther.getMatCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCalCod();
         result = 37 * result + this.getPlaMat();
         result = 37 * result + this.getMatCod();
         return result;
   }   


}


