package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * CalDet generated by hbm2java
 */
public class CalDet  implements java.io.Serializable {


     private CalDetId id;

    public CalDet() {
    }

    public CalDet(CalDetId id) {
       this.id = id;
    }
   
    public CalDetId getId() {
        return this.id;
    }
    
    public void setId(CalDetId id) {
        this.id = id;
    }




}


