package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer carCod;
     private String carDesc;
     private Date carCarg;

    public Carrera() {
    }

    public Carrera(String carDesc, Date carCarg) {
       this.carDesc = carDesc;
       this.carCarg = carCarg;
    }
   
    public Integer getCarCod() {
        return this.carCod;
    }
    
    public void setCarCod(Integer carCod) {
        this.carCod = carCod;
    }
    public String getCarDesc() {
        return this.carDesc;
    }
    
    public void setCarDesc(String carDesc) {
        this.carDesc = carDesc;
    }
    public Date getCarCarg() {
        return this.carCarg;
    }
    
    public void setCarCarg(Date carCarg) {
        this.carCarg = carCarg;
    }




}


