package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Cheque generated by hbm2java
 */
public class Cheque  implements java.io.Serializable {


     private Integer cheCod;
     private String cheDes;
     private int entCod;

    public Cheque() {
    }

	
    public Cheque(int entCod) {
        this.entCod = entCod;
    }
    public Cheque(String cheDes, int entCod) {
       this.cheDes = cheDes;
       this.entCod = entCod;
    }
   
    public Integer getCheCod() {
        return this.cheCod;
    }
    
    public void setCheCod(Integer cheCod) {
        this.cheCod = cheCod;
    }
    public String getCheDes() {
        return this.cheDes;
    }
    
    public void setCheDes(String cheDes) {
        this.cheDes = cheDes;
    }
    public int getEntCod() {
        return this.entCod;
    }
    
    public void setEntCod(int entCod) {
        this.entCod = entCod;
    }




}


