package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * ChequeCobroId generated by hbm2java
 */
public class ChequeCobroId  implements java.io.Serializable {


     private int cheCod;
     private int cobCod;

    public ChequeCobroId() {
    }

    public ChequeCobroId(int cheCod, int cobCod) {
       this.cheCod = cheCod;
       this.cobCod = cobCod;
    }
   
    public int getCheCod() {
        return this.cheCod;
    }
    
    public void setCheCod(int cheCod) {
        this.cheCod = cheCod;
    }
    public int getCobCod() {
        return this.cobCod;
    }
    
    public void setCobCod(int cobCod) {
        this.cobCod = cobCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChequeCobroId) ) return false;
		 ChequeCobroId castOther = ( ChequeCobroId ) other; 
         
		 return (this.getCheCod()==castOther.getCheCod())
 && (this.getCobCod()==castOther.getCobCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCheCod();
         result = 37 * result + this.getCobCod();
         return result;
   }   


}


