package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChequeCobro generated by hbm2java
 */
public class ChequeCobro  implements java.io.Serializable {


     private ChequeCobroId id;
     private String nroCheq;
     private Date fechaEmision;
     private Date fechaCobro;
     private int titCod;

    public ChequeCobro() {
    }

	
    public ChequeCobro(ChequeCobroId id, String nroCheq, int titCod) {
        this.id = id;
        this.nroCheq = nroCheq;
        this.titCod = titCod;
    }
    public ChequeCobro(ChequeCobroId id, String nroCheq, Date fechaEmision, Date fechaCobro, int titCod) {
       this.id = id;
       this.nroCheq = nroCheq;
       this.fechaEmision = fechaEmision;
       this.fechaCobro = fechaCobro;
       this.titCod = titCod;
    }
   
    public ChequeCobroId getId() {
        return this.id;
    }
    
    public void setId(ChequeCobroId id) {
        this.id = id;
    }
    public String getNroCheq() {
        return this.nroCheq;
    }
    
    public void setNroCheq(String nroCheq) {
        this.nroCheq = nroCheq;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public Date getFechaCobro() {
        return this.fechaCobro;
    }
    
    public void setFechaCobro(Date fechaCobro) {
        this.fechaCobro = fechaCobro;
    }
    public int getTitCod() {
        return this.titCod;
    }
    
    public void setTitCod(int titCod) {
        this.titCod = titCod;
    }




}


