package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer ciuCod;
     private String ciuDesc;

    public Ciudad() {
    }

    public Ciudad(String ciuDesc) {
       this.ciuDesc = ciuDesc;
    }
   
    public Integer getCiuCod() {
        return this.ciuCod;
    }
    
    public void setCiuCod(Integer ciuCod) {
        this.ciuCod = ciuCod;
    }
    public String getCiuDesc() {
        return this.ciuDesc;
    }
    
    public void setCiuDesc(String ciuDesc) {
        this.ciuDesc = ciuDesc;
    }




}


