package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * ClasTemId generated by hbm2java
 */
public class ClasTemId  implements java.io.Serializable {


     private int clasCod;
     private int temCod;

    public ClasTemId() {
    }

    public ClasTemId(int clasCod, int temCod) {
       this.clasCod = clasCod;
       this.temCod = temCod;
    }
   
    public int getClasCod() {
        return this.clasCod;
    }
    
    public void setClasCod(int clasCod) {
        this.clasCod = clasCod;
    }
    public int getTemCod() {
        return this.temCod;
    }
    
    public void setTemCod(int temCod) {
        this.temCod = temCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClasTemId) ) return false;
		 ClasTemId castOther = ( ClasTemId ) other; 
         
		 return (this.getClasCod()==castOther.getClasCod())
 && (this.getTemCod()==castOther.getTemCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClasCod();
         result = 37 * result + this.getTemCod();
         return result;
   }   


}


