package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * ClasTem generated by hbm2java
 */
public class ClasTem  implements java.io.Serializable {


     private ClasTemId id;
     private String clasDesc;

    public ClasTem() {
    }

	
    public ClasTem(ClasTemId id) {
        this.id = id;
    }
    public ClasTem(ClasTemId id, String clasDesc) {
       this.id = id;
       this.clasDesc = clasDesc;
    }
   
    public ClasTemId getId() {
        return this.id;
    }
    
    public void setId(ClasTemId id) {
        this.id = id;
    }
    public String getClasDesc() {
        return this.clasDesc;
    }
    
    public void setClasDesc(String clasDesc) {
        this.clasDesc = clasDesc;
    }




}


