package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Cobro generated by hbm2java
 */
public class Cobro  implements java.io.Serializable {


     private CobroId id;
     private int fpgCod;

    public Cobro() {
    }

    public Cobro(CobroId id, int fpgCod) {
       this.id = id;
       this.fpgCod = fpgCod;
    }
   
    public CobroId getId() {
        return this.id;
    }
    
    public void setId(CobroId id) {
        this.id = id;
    }
    public int getFpgCod() {
        return this.fpgCod;
    }
    
    public void setFpgCod(int fpgCod) {
        this.fpgCod = fpgCod;
    }




}


