package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cuotas generated by hbm2java
 */
public class Cuotas  implements java.io.Serializable {


     private Integer cuoCod;
     private Double cuoCosto;
     private Character estado;
     private Date cuoFechaVenci;
     private Date fechaActualizacion;
     private int insCod;
     private int perCod;

    public Cuotas() {
    }

	
    public Cuotas(int insCod, int perCod) {
        this.insCod = insCod;
        this.perCod = perCod;
    }
    public Cuotas(Double cuoCosto, Character estado, Date cuoFechaVenci, Date fechaActualizacion, int insCod, int perCod) {
       this.cuoCosto = cuoCosto;
       this.estado = estado;
       this.cuoFechaVenci = cuoFechaVenci;
       this.fechaActualizacion = fechaActualizacion;
       this.insCod = insCod;
       this.perCod = perCod;
    }
   
    public Integer getCuoCod() {
        return this.cuoCod;
    }
    
    public void setCuoCod(Integer cuoCod) {
        this.cuoCod = cuoCod;
    }
    public Double getCuoCosto() {
        return this.cuoCosto;
    }
    
    public void setCuoCosto(Double cuoCosto) {
        this.cuoCosto = cuoCosto;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Date getCuoFechaVenci() {
        return this.cuoFechaVenci;
    }
    
    public void setCuoFechaVenci(Date cuoFechaVenci) {
        this.cuoFechaVenci = cuoFechaVenci;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public int getInsCod() {
        return this.insCod;
    }
    
    public void setInsCod(int insCod) {
        this.insCod = insCod;
    }
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }




}


