package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer curCod;
     private String descripcion;

    public Curso() {
    }

    public Curso(String descripcion) {
       this.descripcion = descripcion;
    }
   
    public Integer getCurCod() {
        return this.curCod;
    }
    
    public void setCurCod(Integer curCod) {
        this.curCod = curCod;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


