package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * DevDet generated by hbm2java
 */
public class DevDet  implements java.io.Serializable {


     private DevDetId id;
     private Character devEstado;

    public DevDet() {
    }

	
    public DevDet(DevDetId id) {
        this.id = id;
    }
    public DevDet(DevDetId id, Character devEstado) {
       this.id = id;
       this.devEstado = devEstado;
    }
   
    public DevDetId getId() {
        return this.id;
    }
    
    public void setId(DevDetId id) {
        this.id = id;
    }
    public Character getDevEstado() {
        return this.devEstado;
    }
    
    public void setDevEstado(Character devEstado) {
        this.devEstado = devEstado;
    }




}


