package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Devolucion generated by hbm2java
 */
public class Devolucion  implements java.io.Serializable {


     private DevolucionId id;
     private Date devCarg;
     private Date devFec;
     private Character preEstado;

    public Devolucion() {
    }

	
    public Devolucion(DevolucionId id) {
        this.id = id;
    }
    public Devolucion(DevolucionId id, Date devCarg, Date devFec, Character preEstado) {
       this.id = id;
       this.devCarg = devCarg;
       this.devFec = devFec;
       this.preEstado = preEstado;
    }
   
    public DevolucionId getId() {
        return this.id;
    }
    
    public void setId(DevolucionId id) {
        this.id = id;
    }
    public Date getDevCarg() {
        return this.devCarg;
    }
    
    public void setDevCarg(Date devCarg) {
        this.devCarg = devCarg;
    }
    public Date getDevFec() {
        return this.devFec;
    }
    
    public void setDevFec(Date devFec) {
        this.devFec = devFec;
    }
    public Character getPreEstado() {
        return this.preEstado;
    }
    
    public void setPreEstado(Character preEstado) {
        this.preEstado = preEstado;
    }




}


