package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * DevolucionId generated by hbm2java
 */
public class DevolucionId  implements java.io.Serializable {


     private int devCod;
     private int preCod;

    public DevolucionId() {
    }

    public DevolucionId(int devCod, int preCod) {
       this.devCod = devCod;
       this.preCod = preCod;
    }
   
    public int getDevCod() {
        return this.devCod;
    }
    
    public void setDevCod(int devCod) {
        this.devCod = devCod;
    }
    public int getPreCod() {
        return this.preCod;
    }
    
    public void setPreCod(int preCod) {
        this.preCod = preCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DevolucionId) ) return false;
		 DevolucionId castOther = ( DevolucionId ) other; 
         
		 return (this.getDevCod()==castOther.getDevCod())
 && (this.getPreCod()==castOther.getPreCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDevCod();
         result = 37 * result + this.getPreCod();
         return result;
   }   


}


