package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * EdiSell generated by hbm2java
 */
public class EdiSell  implements java.io.Serializable {


     private Integer ediCod;
     private String ediDesc;
     private String ediWeb;
     private String ediCon;
     private String ediTel;

    public EdiSell() {
    }

    public EdiSell(String ediDesc, String ediWeb, String ediCon, String ediTel) {
       this.ediDesc = ediDesc;
       this.ediWeb = ediWeb;
       this.ediCon = ediCon;
       this.ediTel = ediTel;
    }
   
    public Integer getEdiCod() {
        return this.ediCod;
    }
    
    public void setEdiCod(Integer ediCod) {
        this.ediCod = ediCod;
    }
    public String getEdiDesc() {
        return this.ediDesc;
    }
    
    public void setEdiDesc(String ediDesc) {
        this.ediDesc = ediDesc;
    }
    public String getEdiWeb() {
        return this.ediWeb;
    }
    
    public void setEdiWeb(String ediWeb) {
        this.ediWeb = ediWeb;
    }
    public String getEdiCon() {
        return this.ediCon;
    }
    
    public void setEdiCon(String ediCon) {
        this.ediCon = ediCon;
    }
    public String getEdiTel() {
        return this.ediTel;
    }
    
    public void setEdiTel(String ediTel) {
        this.ediTel = ediTel;
    }




}


