package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * FacturacionId generated by hbm2java
 */
public class FacturacionId  implements java.io.Serializable {


     private int facCod;
     private int apciCod;
     private int usuCod;
     private int sucCod;
     private int cajCod;

    public FacturacionId() {
    }

    public FacturacionId(int facCod, int apciCod, int usuCod, int sucCod, int cajCod) {
       this.facCod = facCod;
       this.apciCod = apciCod;
       this.usuCod = usuCod;
       this.sucCod = sucCod;
       this.cajCod = cajCod;
    }
   
    public int getFacCod() {
        return this.facCod;
    }
    
    public void setFacCod(int facCod) {
        this.facCod = facCod;
    }
    public int getApciCod() {
        return this.apciCod;
    }
    
    public void setApciCod(int apciCod) {
        this.apciCod = apciCod;
    }
    public int getUsuCod() {
        return this.usuCod;
    }
    
    public void setUsuCod(int usuCod) {
        this.usuCod = usuCod;
    }
    public int getSucCod() {
        return this.sucCod;
    }
    
    public void setSucCod(int sucCod) {
        this.sucCod = sucCod;
    }
    public int getCajCod() {
        return this.cajCod;
    }
    
    public void setCajCod(int cajCod) {
        this.cajCod = cajCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturacionId) ) return false;
		 FacturacionId castOther = ( FacturacionId ) other; 
         
		 return (this.getFacCod()==castOther.getFacCod())
 && (this.getApciCod()==castOther.getApciCod())
 && (this.getUsuCod()==castOther.getUsuCod())
 && (this.getSucCod()==castOther.getSucCod())
 && (this.getCajCod()==castOther.getCajCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFacCod();
         result = 37 * result + this.getApciCod();
         result = 37 * result + this.getUsuCod();
         result = 37 * result + this.getSucCod();
         result = 37 * result + this.getCajCod();
         return result;
   }   


}


