package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * FacturacionDetalle generated by hbm2java
 */
public class FacturacionDetalle  implements java.io.Serializable {


     private FacturacionDetalleId id;
     private Double facCosto;

    public FacturacionDetalle() {
    }

	
    public FacturacionDetalle(FacturacionDetalleId id) {
        this.id = id;
    }
    public FacturacionDetalle(FacturacionDetalleId id, Double facCosto) {
       this.id = id;
       this.facCosto = facCosto;
    }
   
    public FacturacionDetalleId getId() {
        return this.id;
    }
    
    public void setId(FacturacionDetalleId id) {
        this.id = id;
    }
    public Double getFacCosto() {
        return this.facCosto;
    }
    
    public void setFacCosto(Double facCosto) {
        this.facCosto = facCosto;
    }




}


