package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * FacturacionDetalleId generated by hbm2java
 */
public class FacturacionDetalleId  implements java.io.Serializable {


     private int facCod;
     private int cuoCod;

    public FacturacionDetalleId() {
    }

    public FacturacionDetalleId(int facCod, int cuoCod) {
       this.facCod = facCod;
       this.cuoCod = cuoCod;
    }
   
    public int getFacCod() {
        return this.facCod;
    }
    
    public void setFacCod(int facCod) {
        this.facCod = facCod;
    }
    public int getCuoCod() {
        return this.cuoCod;
    }
    
    public void setCuoCod(int cuoCod) {
        this.cuoCod = cuoCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturacionDetalleId) ) return false;
		 FacturacionDetalleId castOther = ( FacturacionDetalleId ) other; 
         
		 return (this.getFacCod()==castOther.getFacCod())
 && (this.getCuoCod()==castOther.getCuoCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFacCod();
         result = 37 * result + this.getCuoCod();
         return result;
   }   


}


