package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * FormaAca generated by hbm2java
 */
public class FormaAca  implements java.io.Serializable {


     private FormaAcaId id;
     private int nivCod;
     private String forLugarEst;
     private int titCod;

    public FormaAca() {
    }

	
    public FormaAca(FormaAcaId id, int nivCod, int titCod) {
        this.id = id;
        this.nivCod = nivCod;
        this.titCod = titCod;
    }
    public FormaAca(FormaAcaId id, int nivCod, String forLugarEst, int titCod) {
       this.id = id;
       this.nivCod = nivCod;
       this.forLugarEst = forLugarEst;
       this.titCod = titCod;
    }
   
    public FormaAcaId getId() {
        return this.id;
    }
    
    public void setId(FormaAcaId id) {
        this.id = id;
    }
    public int getNivCod() {
        return this.nivCod;
    }
    
    public void setNivCod(int nivCod) {
        this.nivCod = nivCod;
    }
    public String getForLugarEst() {
        return this.forLugarEst;
    }
    
    public void setForLugarEst(String forLugarEst) {
        this.forLugarEst = forLugarEst;
    }
    public int getTitCod() {
        return this.titCod;
    }
    
    public void setTitCod(int titCod) {
        this.titCod = titCod;
    }




}


