package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private InscripcionId id;
     private Boolean esLider;
     private Boolean insEdl;
     private Boolean insEv;
     private String insOtro;
     private String comentario;
     private Date insCarg;
     private Character insEstado;
     private int usuCod;
     private int sucCod;
     private int plaCod;
     private int malCod;
     private int carCod;
     private int curCod;
     private Boolean insFirm;
     private Boolean insAcl;

    public Inscripcion() {
    }

	
    public Inscripcion(InscripcionId id, int usuCod, int sucCod, int plaCod, int malCod, int carCod, int curCod) {
        this.id = id;
        this.usuCod = usuCod;
        this.sucCod = sucCod;
        this.plaCod = plaCod;
        this.malCod = malCod;
        this.carCod = carCod;
        this.curCod = curCod;
    }
    public Inscripcion(InscripcionId id, Boolean esLider, Boolean insEdl, Boolean insEv, String insOtro, String comentario, Date insCarg, Character insEstado, int usuCod, int sucCod, int plaCod, int malCod, int carCod, int curCod, Boolean insFirm, Boolean insAcl) {
       this.id = id;
       this.esLider = esLider;
       this.insEdl = insEdl;
       this.insEv = insEv;
       this.insOtro = insOtro;
       this.comentario = comentario;
       this.insCarg = insCarg;
       this.insEstado = insEstado;
       this.usuCod = usuCod;
       this.sucCod = sucCod;
       this.plaCod = plaCod;
       this.malCod = malCod;
       this.carCod = carCod;
       this.curCod = curCod;
       this.insFirm = insFirm;
       this.insAcl = insAcl;
    }
   
    public InscripcionId getId() {
        return this.id;
    }
    
    public void setId(InscripcionId id) {
        this.id = id;
    }
    public Boolean getEsLider() {
        return this.esLider;
    }
    
    public void setEsLider(Boolean esLider) {
        this.esLider = esLider;
    }
    public Boolean getInsEdl() {
        return this.insEdl;
    }
    
    public void setInsEdl(Boolean insEdl) {
        this.insEdl = insEdl;
    }
    public Boolean getInsEv() {
        return this.insEv;
    }
    
    public void setInsEv(Boolean insEv) {
        this.insEv = insEv;
    }
    public String getInsOtro() {
        return this.insOtro;
    }
    
    public void setInsOtro(String insOtro) {
        this.insOtro = insOtro;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getInsCarg() {
        return this.insCarg;
    }
    
    public void setInsCarg(Date insCarg) {
        this.insCarg = insCarg;
    }
    public Character getInsEstado() {
        return this.insEstado;
    }
    
    public void setInsEstado(Character insEstado) {
        this.insEstado = insEstado;
    }
    public int getUsuCod() {
        return this.usuCod;
    }
    
    public void setUsuCod(int usuCod) {
        this.usuCod = usuCod;
    }
    public int getSucCod() {
        return this.sucCod;
    }
    
    public void setSucCod(int sucCod) {
        this.sucCod = sucCod;
    }
    public int getPlaCod() {
        return this.plaCod;
    }
    
    public void setPlaCod(int plaCod) {
        this.plaCod = plaCod;
    }
    public int getMalCod() {
        return this.malCod;
    }
    
    public void setMalCod(int malCod) {
        this.malCod = malCod;
    }
    public int getCarCod() {
        return this.carCod;
    }
    
    public void setCarCod(int carCod) {
        this.carCod = carCod;
    }
    public int getCurCod() {
        return this.curCod;
    }
    
    public void setCurCod(int curCod) {
        this.curCod = curCod;
    }
    public Boolean getInsFirm() {
        return this.insFirm;
    }
    
    public void setInsFirm(Boolean insFirm) {
        this.insFirm = insFirm;
    }
    public Boolean getInsAcl() {
        return this.insAcl;
    }
    
    public void setInsAcl(Boolean insAcl) {
        this.insAcl = insAcl;
    }




}


