package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * InscripcionId generated by hbm2java
 */
public class InscripcionId  implements java.io.Serializable {


     private int insCod;
     private int perCod;

    public InscripcionId() {
    }

    public InscripcionId(int insCod, int perCod) {
       this.insCod = insCod;
       this.perCod = perCod;
    }
   
    public int getInsCod() {
        return this.insCod;
    }
    
    public void setInsCod(int insCod) {
        this.insCod = insCod;
    }
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InscripcionId) ) return false;
		 InscripcionId castOther = ( InscripcionId ) other; 
         
		 return (this.getInsCod()==castOther.getInsCod())
 && (this.getPerCod()==castOther.getPerCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInsCod();
         result = 37 * result + this.getPerCod();
         return result;
   }   


}


