package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Malla generated by hbm2java
 */
public class Malla  implements java.io.Serializable {

    // private MallaId id;
     private int malCod;
     private int carCod;
     private Date malCarg;
     private Date malInicio;
     private Date malFin;
     private Character malEstado;
     private int usuCod;
     private int sucCod;

    public Malla() {
    }

	
    public Malla(int malCod,int carCod, int usuCod, int sucCod) {
        //this.id = id;
        this.malCod = malCod;
        this.carCod=carCod;
        this.usuCod = usuCod;
        this.sucCod = sucCod;
    }
    public Malla(int malCod,int carCod, Date malCarg, Date malInicio, Date malFin, Character malEstado, int usuCod, int sucCod) {
       //this.id = id;
       this.malCod = malCod;
       this.carCod=carCod;
       this.malCarg = malCarg;
       this.malInicio = malInicio;
       this.malFin = malFin;
       this.malEstado = malEstado;
       this.usuCod = usuCod;
       this.sucCod = sucCod;
    }
   
   /* public MallaId getId() {
        return this.id;
    }
    
    public void setId(MallaId id) {
        this.id = id;
    }*/
    public Date getMalCarg() {
        return this.malCarg;
    }
    
    public void setMalCarg(Date malCarg) {
        this.malCarg = malCarg;
    }
    public Date getMalInicio() {
        return this.malInicio;
    }
    
    public void setMalInicio(Date malInicio) {
        this.malInicio = malInicio;
    }
    public Date getMalFin() {
        return this.malFin;
    }
    
    public void setMalFin(Date malFin) {
        this.malFin = malFin;
    }
    public Character getMalEstado() {
        return this.malEstado;
    }
    
    public void setMalEstado(Character malEstado) {
        this.malEstado = malEstado;
    }

    public int getMalCod() {
        return malCod;
    }

    public void setMalCod(int malCod) {
        this.malCod = malCod;
    }

    public int getCarCod() {
        return carCod;
    }

    public void setCarCod(int carCod) {
        this.carCod = carCod;
    }
    
    public int getUsuCod() {
        return this.usuCod;
    }
    
    public void setUsuCod(int usuCod) {
        this.usuCod = usuCod;
    }
    public int getSucCod() {
        return this.sucCod;
    }
    
    public void setSucCod(int sucCod) {
        this.sucCod = sucCod;
    }




}


