package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * MallaDet generated by hbm2java
 */
public class MallaDet  implements java.io.Serializable {


     private int mallaCurricular;
     private int matCod;
     private Character malEstado;

    public MallaDet() {
    }

	
    public MallaDet(int mallaCurricular, int matCod) {
        this.mallaCurricular = mallaCurricular;
        this.matCod = matCod;
    }
    public MallaDet(int mallaCurricular, int matCod, Character malEstado) {
       this.mallaCurricular = mallaCurricular;
       this.matCod = matCod;
       this.malEstado = malEstado;
    }
   
    public int getMallaCurricular() {
        return this.mallaCurricular;
    }
    
    public void setMallaCurricular(int mallaCurricular) {
        this.mallaCurricular = mallaCurricular;
    }
    public int getMatCod() {
        return this.matCod;
    }
    
    public void setMatCod(int matCod) {
        this.matCod = matCod;
    }
    public Character getMalEstado() {
        return this.malEstado;
    }
    
    public void setMalEstado(Character malEstado) {
        this.malEstado = malEstado;
    }




}


