package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * MallaDet generated by hbm2java
 */
public class MallaDet  implements java.io.Serializable {


     private int malCod;
     private int matCod;
     private String matDesc;
     private String matIden;
     private Malla malla;
     private Materia materia;
     private Character malEstado;

    public MallaDet() {
    }

	
    public MallaDet(Malla malla,Materia materia,int malCod, int matCod,String matDesc) {
        this.malla = malla;
        this.matDesc = matDesc;
        //this.matIden= matIden;
        this.materia = materia;
        this.malCod = malCod;
        this.matCod = matCod;
    }
    public MallaDet(Malla malla,Materia materia,int malCod, int matCod,String matDesc, Character malEstado) {
       this.malla=malla;
       this.matDesc = matDesc;
       //this.matIden = matIden;
       this.materia=materia;
       this.malCod = malCod;
       this.matCod = matCod;
       this.malEstado = malEstado;
    }
   
    public int getMalCod() {
        return this.malCod;
    }
    
    public void setMalCod(int malCod) {
        this.malCod = malCod;
    }
    public int getMatCod() {
        return this.matCod;
    }
    
    public void setMatCod(int matCod) {
        this.matCod = matCod;
    }
    public Character getMalEstado() {
        return this.malEstado;
    }
    
    public void setMalEstado(Character malEstado) {
        this.malEstado = malEstado;
    }

    public Malla getMalla() {
        return malla;
    }

    public void setMalla(Malla malla) {
        this.malla = malla;
    }

    public Materia getMateria() {
        return materia;
    }

    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    public String getMatDesc() {
        return matDesc;
    }

    public void setMatDesc(String matDesc) {
        this.matDesc = matDesc;
    }

    public String getMatIden() {
        return matIden;
    }

    public void setMatIden(String matIden) {
        this.matIden = matIden;
    }
    



}


