package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer matCod;
     private String matIden;
     private String matDesc;
     private Integer matCred;
     private int uniCod;
     private int semCod;
     private int curCod;

    public Materia() {
    }

	
    public Materia(String matIden, int uniCod, int semCod, int curCod) {
        this.matIden = matIden;
        this.uniCod = uniCod;
        this.semCod = semCod;
        this.curCod = curCod;
    }
    public Materia(String matIden, String matDesc, Integer matCred, int uniCod, int semCod, int curCod) {
       this.matIden = matIden;
       this.matDesc = matDesc;
       this.matCred = matCred;
       this.uniCod = uniCod;
       this.semCod = semCod;
       this.curCod = curCod;
    }
   
    public Integer getMatCod() {
        return this.matCod;
    }
    
    public void setMatCod(Integer matCod) {
        this.matCod = matCod;
    }
    public String getMatIden() {
        return this.matIden;
    }
    
    public void setMatIden(String matIden) {
        this.matIden = matIden;
    }
    public String getMatDesc() {
        return this.matDesc;
    }
    
    public void setMatDesc(String matDesc) {
        this.matDesc = matDesc;
    }
    public Integer getMatCred() {
        return this.matCred;
    }
    
    public void setMatCred(Integer matCred) {
        this.matCred = matCred;
    }
    public int getUniCod() {
        return this.uniCod;
    }
    
    public void setUniCod(int uniCod) {
        this.uniCod = uniCod;
    }
    public int getSemCod() {
        return this.semCod;
    }
    
    public void setSemCod(int semCod) {
        this.semCod = semCod;
    }
    public int getCurCod() {
        return this.curCod;
    }
    
    public void setCurCod(int curCod) {
        this.curCod = curCod;
    }




}


