package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Nacionalidad generated by hbm2java
 */
public class Nacionalidad  implements java.io.Serializable {


     private int nacCod;
     private String nacDesc;
     private String nacAbre;

    public Nacionalidad() {
    }

	
    public Nacionalidad(int nacCod) {
        this.nacCod = nacCod;
    }
    public Nacionalidad(int nacCod, String nacDesc, String nacAbre) {
       this.nacCod = nacCod;
       this.nacDesc = nacDesc;
       this.nacAbre = nacAbre;
    }
   
    public int getNacCod() {
        return this.nacCod;
    }
    
    public void setNacCod(int nacCod) {
        this.nacCod = nacCod;
    }
    public String getNacDesc() {
        return this.nacDesc;
    }
    
    public void setNacDesc(String nacDesc) {
        this.nacDesc = nacDesc;
    }
    public String getNacAbre() {
        return this.nacAbre;
    }
    
    public void setNacAbre(String nacAbre) {
        this.nacAbre = nacAbre;
    }




}


