package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * NivelEst generated by hbm2java
 */
public class NivelEst  implements java.io.Serializable {


     private Integer nivCod;
     private String nivDesc;

    public NivelEst() {
    }

    public NivelEst(String nivDesc) {
       this.nivDesc = nivDesc;
    }
   
    public Integer getNivCod() {
        return this.nivCod;
    }
    
    public void setNivCod(Integer nivCod) {
        this.nivCod = nivCod;
    }
    public String getNivDesc() {
        return this.nivDesc;
    }
    
    public void setNivDesc(String nivDesc) {
        this.nivDesc = nivDesc;
    }




}


