package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Organizacion generated by hbm2java
 */
public class Organizacion  implements java.io.Serializable {


     private Integer orgCod;
     private String orgDesc;
     private int perCod;
     private String orgDir;
     private String orgTel;
     private String orgCel;
     private String orgWeb;

    public Organizacion() {
    }

	
    public Organizacion(int perCod) {
        this.perCod = perCod;
    }
    public Organizacion(String orgDesc, int perCod, String orgDir, String orgTel, String orgCel, String orgWeb) {
       this.orgDesc = orgDesc;
       this.perCod = perCod;
       this.orgDir = orgDir;
       this.orgTel = orgTel;
       this.orgCel = orgCel;
       this.orgWeb = orgWeb;
    }
   
    public Integer getOrgCod() {
        return this.orgCod;
    }
    
    public void setOrgCod(Integer orgCod) {
        this.orgCod = orgCod;
    }
    public String getOrgDesc() {
        return this.orgDesc;
    }
    
    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc;
    }
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }
    public String getOrgDir() {
        return this.orgDir;
    }
    
    public void setOrgDir(String orgDir) {
        this.orgDir = orgDir;
    }
    public String getOrgTel() {
        return this.orgTel;
    }
    
    public void setOrgTel(String orgTel) {
        this.orgTel = orgTel;
    }
    public String getOrgCel() {
        return this.orgCel;
    }
    
    public void setOrgCel(String orgCel) {
        this.orgCel = orgCel;
    }
    public String getOrgWeb() {
        return this.orgWeb;
    }
    
    public void setOrgWeb(String orgWeb) {
        this.orgWeb = orgWeb;
    }




}


