package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer perCod;
     private String perNom;
     private String perApe;
     private String perTpDoc;
     private String perNroDoc;
     private Date perFecNac;
     private String perCalle;
     private String perNroCasa;
     private String perCallSec;
     private String perTel;
     private String perCel;
     private String perEmail;
     private int ciuCod;
     private int barCod;
     private int nacCod;
     private int actCod;
     private Date perCarg;
     private String perClas;
     private int profCod;

    public Persona() {
    }

	
    public Persona(int ciuCod, int barCod, int nacCod, int actCod, int profCod) {
        this.ciuCod = ciuCod;
        this.barCod = barCod;
        this.nacCod = nacCod;
        this.actCod = actCod;
        this.profCod = profCod;
    }
    public Persona(String perNom, String perApe, String perTpDoc, String perNroDoc, Date perFecNac, String perCalle, String perNroCasa, String perCallSec, String perTel, String perCel, String perEmail, int ciuCod, int barCod, int nacCod, int actCod, Date perCarg, String perClas, int profCod) {
       this.perNom = perNom;
       this.perApe = perApe;
       this.perTpDoc = perTpDoc;
       this.perNroDoc = perNroDoc;
       this.perFecNac = perFecNac;
       this.perCalle = perCalle;
       this.perNroCasa = perNroCasa;
       this.perCallSec = perCallSec;
       this.perTel = perTel;
       this.perCel = perCel;
       this.perEmail = perEmail;
       this.ciuCod = ciuCod;
       this.barCod = barCod;
       this.nacCod = nacCod;
       this.actCod = actCod;
       this.perCarg = perCarg;
       this.perClas = perClas;
       this.profCod = profCod;
    }
   
    public Integer getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(Integer perCod) {
        this.perCod = perCod;
    }
    public String getPerNom() {
        return this.perNom;
    }
    
    public void setPerNom(String perNom) {
        this.perNom = perNom;
    }
    public String getPerApe() {
        return this.perApe;
    }
    
    public void setPerApe(String perApe) {
        this.perApe = perApe;
    }
    public String getPerTpDoc() {
        return this.perTpDoc;
    }
    
    public void setPerTpDoc(String perTpDoc) {
        this.perTpDoc = perTpDoc;
    }
    public String getPerNroDoc() {
        return this.perNroDoc;
    }
    
    public void setPerNroDoc(String perNroDoc) {
        this.perNroDoc = perNroDoc;
    }
    public Date getPerFecNac() {
        return this.perFecNac;
    }
    
    public void setPerFecNac(Date perFecNac) {
        this.perFecNac = perFecNac;
    }
    public String getPerCalle() {
        return this.perCalle;
    }
    
    public void setPerCalle(String perCalle) {
        this.perCalle = perCalle;
    }
    public String getPerNroCasa() {
        return this.perNroCasa;
    }
    
    public void setPerNroCasa(String perNroCasa) {
        this.perNroCasa = perNroCasa;
    }
    public String getPerCallSec() {
        return this.perCallSec;
    }
    
    public void setPerCallSec(String perCallSec) {
        this.perCallSec = perCallSec;
    }
    public String getPerTel() {
        return this.perTel;
    }
    
    public void setPerTel(String perTel) {
        this.perTel = perTel;
    }
    public String getPerCel() {
        return this.perCel;
    }
    
    public void setPerCel(String perCel) {
        this.perCel = perCel;
    }
    public String getPerEmail() {
        return this.perEmail;
    }
    
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail;
    }
    public int getCiuCod() {
        return this.ciuCod;
    }
    
    public void setCiuCod(int ciuCod) {
        this.ciuCod = ciuCod;
    }
    public int getBarCod() {
        return this.barCod;
    }
    
    public void setBarCod(int barCod) {
        this.barCod = barCod;
    }
    public int getNacCod() {
        return this.nacCod;
    }
    
    public void setNacCod(int nacCod) {
        this.nacCod = nacCod;
    }
    public int getActCod() {
        return this.actCod;
    }
    
    public void setActCod(int actCod) {
        this.actCod = actCod;
    }
    public Date getPerCarg() {
        return this.perCarg;
    }
    
    public void setPerCarg(Date perCarg) {
        this.perCarg = perCarg;
    }
    public String getPerClas() {
        return this.perClas;
    }
    
    public void setPerClas(String perClas) {
        this.perClas = perClas;
    }
    public int getProfCod() {
        return this.profCod;
    }
    
    public void setProfCod(int profCod) {
        this.profCod = profCod;
    }




}


