package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * PlaAsistenciaDet generated by hbm2java
 */
public class PlaAsistenciaDet  implements java.io.Serializable {


     private PlaAsistenciaDetId id;
     private Boolean auno;
     private Boolean ados;
     private Boolean atres;
     private Boolean acuatro;
     private Boolean acinco;
     private Boolean aseis;
     private Boolean asiete;
     private Boolean aocho;
     private Boolean anueve;

    public PlaAsistenciaDet() {
    }

	
    public PlaAsistenciaDet(PlaAsistenciaDetId id) {
        this.id = id;
    }
    public PlaAsistenciaDet(PlaAsistenciaDetId id, Boolean auno, Boolean ados, Boolean atres, Boolean acuatro, Boolean acinco, Boolean aseis, Boolean asiete, Boolean aocho, Boolean anueve) {
       this.id = id;
       this.auno = auno;
       this.ados = ados;
       this.atres = atres;
       this.acuatro = acuatro;
       this.acinco = acinco;
       this.aseis = aseis;
       this.asiete = asiete;
       this.aocho = aocho;
       this.anueve = anueve;
    }
   
    public PlaAsistenciaDetId getId() {
        return this.id;
    }
    
    public void setId(PlaAsistenciaDetId id) {
        this.id = id;
    }
    public Boolean getAuno() {
        return this.auno;
    }
    
    public void setAuno(Boolean auno) {
        this.auno = auno;
    }
    public Boolean getAdos() {
        return this.ados;
    }
    
    public void setAdos(Boolean ados) {
        this.ados = ados;
    }
    public Boolean getAtres() {
        return this.atres;
    }
    
    public void setAtres(Boolean atres) {
        this.atres = atres;
    }
    public Boolean getAcuatro() {
        return this.acuatro;
    }
    
    public void setAcuatro(Boolean acuatro) {
        this.acuatro = acuatro;
    }
    public Boolean getAcinco() {
        return this.acinco;
    }
    
    public void setAcinco(Boolean acinco) {
        this.acinco = acinco;
    }
    public Boolean getAseis() {
        return this.aseis;
    }
    
    public void setAseis(Boolean aseis) {
        this.aseis = aseis;
    }
    public Boolean getAsiete() {
        return this.asiete;
    }
    
    public void setAsiete(Boolean asiete) {
        this.asiete = asiete;
    }
    public Boolean getAocho() {
        return this.aocho;
    }
    
    public void setAocho(Boolean aocho) {
        this.aocho = aocho;
    }
    public Boolean getAnueve() {
        return this.anueve;
    }
    
    public void setAnueve(Boolean anueve) {
        this.anueve = anueve;
    }




}


