package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * PlaAsistenciaDetId generated by hbm2java
 */
public class PlaAsistenciaDetId  implements java.io.Serializable {


     private int insCod;
     private int perCod;
     private int plaCod;
     private int plaMat;
     private int matCod;

    public PlaAsistenciaDetId() {
    }

    public PlaAsistenciaDetId(int insCod, int perCod, int plaCod, int plaMat, int matCod) {
       this.insCod = insCod;
       this.perCod = perCod;
       this.plaCod = plaCod;
       this.plaMat = plaMat;
       this.matCod = matCod;
    }
   
    public int getInsCod() {
        return this.insCod;
    }
    
    public void setInsCod(int insCod) {
        this.insCod = insCod;
    }
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }
    public int getPlaCod() {
        return this.plaCod;
    }
    
    public void setPlaCod(int plaCod) {
        this.plaCod = plaCod;
    }
    public int getPlaMat() {
        return this.plaMat;
    }
    
    public void setPlaMat(int plaMat) {
        this.plaMat = plaMat;
    }
    public int getMatCod() {
        return this.matCod;
    }
    
    public void setMatCod(int matCod) {
        this.matCod = matCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlaAsistenciaDetId) ) return false;
		 PlaAsistenciaDetId castOther = ( PlaAsistenciaDetId ) other; 
         
		 return (this.getInsCod()==castOther.getInsCod())
 && (this.getPerCod()==castOther.getPerCod())
 && (this.getPlaCod()==castOther.getPlaCod())
 && (this.getPlaMat()==castOther.getPlaMat())
 && (this.getMatCod()==castOther.getMatCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInsCod();
         result = 37 * result + this.getPerCod();
         result = 37 * result + this.getPlaCod();
         result = 37 * result + this.getPlaMat();
         result = 37 * result + this.getMatCod();
         return result;
   }   


}


