package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PlanCurso generated by hbm2java
 */
public class PlanCurso  implements java.io.Serializable {


     private PlanCursoId id;
     private Date plaCarga;
     private Date plaInicio;
     private Date plaFin;
     private String plaTurno;
     private String plaModalidad;
     private Character plaEstado;
     private Boolean lun;
     private Boolean mar;
     private Boolean mie;
     private Boolean jue;
     private Boolean vie;
     private Boolean sab;
     private Integer plaCupo;

    public PlanCurso() {
    }

	
    public PlanCurso(PlanCursoId id) {
        this.id = id;
    }
    public PlanCurso(PlanCursoId id, Date plaCarga, Date plaInicio, Date plaFin, String plaTurno, String plaModalidad, Character plaEstado, Boolean lun, Boolean mar, Boolean mie, Boolean jue, Boolean vie, Boolean sab, Integer plaCupo) {
       this.id = id;
       this.plaCarga = plaCarga;
       this.plaInicio = plaInicio;
       this.plaFin = plaFin;
       this.plaTurno = plaTurno;
       this.plaModalidad = plaModalidad;
       this.plaEstado = plaEstado;
       this.lun = lun;
       this.mar = mar;
       this.mie = mie;
       this.jue = jue;
       this.vie = vie;
       this.sab = sab;
       this.plaCupo = plaCupo;
    }
   
    public PlanCursoId getId() {
        return this.id;
    }
    
    public void setId(PlanCursoId id) {
        this.id = id;
    }
    public Date getPlaCarga() {
        return this.plaCarga;
    }
    
    public void setPlaCarga(Date plaCarga) {
        this.plaCarga = plaCarga;
    }
    public Date getPlaInicio() {
        return this.plaInicio;
    }
    
    public void setPlaInicio(Date plaInicio) {
        this.plaInicio = plaInicio;
    }
    public Date getPlaFin() {
        return this.plaFin;
    }
    
    public void setPlaFin(Date plaFin) {
        this.plaFin = plaFin;
    }
    public String getPlaTurno() {
        return this.plaTurno;
    }
    
    public void setPlaTurno(String plaTurno) {
        this.plaTurno = plaTurno;
    }
    public String getPlaModalidad() {
        return this.plaModalidad;
    }
    
    public void setPlaModalidad(String plaModalidad) {
        this.plaModalidad = plaModalidad;
    }
    public Character getPlaEstado() {
        return this.plaEstado;
    }
    
    public void setPlaEstado(Character plaEstado) {
        this.plaEstado = plaEstado;
    }
    public Boolean getLun() {
        return this.lun;
    }
    
    public void setLun(Boolean lun) {
        this.lun = lun;
    }
    public Boolean getMar() {
        return this.mar;
    }
    
    public void setMar(Boolean mar) {
        this.mar = mar;
    }
    public Boolean getMie() {
        return this.mie;
    }
    
    public void setMie(Boolean mie) {
        this.mie = mie;
    }
    public Boolean getJue() {
        return this.jue;
    }
    
    public void setJue(Boolean jue) {
        this.jue = jue;
    }
    public Boolean getVie() {
        return this.vie;
    }
    
    public void setVie(Boolean vie) {
        this.vie = vie;
    }
    public Boolean getSab() {
        return this.sab;
    }
    
    public void setSab(Boolean sab) {
        this.sab = sab;
    }
    public Integer getPlaCupo() {
        return this.plaCupo;
    }
    
    public void setPlaCupo(Integer plaCupo) {
        this.plaCupo = plaCupo;
    }




}


