package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PlanMateria generated by hbm2java
 */
public class PlanMateria  implements java.io.Serializable {


     private PlanMateriaId id;
     private int proCod;
     private Boolean lunes;
     private Boolean martes;
     private Boolean miercoles;
     private Boolean jueves;
     private Boolean viernes;
     private Boolean sabados;
     private Date plaMatIni;
     private Date plaMatFin;
     private String plaMatBim;
     private Integer plaMatHpe;
     private int usuCod;
     private int sucCod;

    public PlanMateria() {
    }

	
    public PlanMateria(PlanMateriaId id, int proCod, int usuCod, int sucCod) {
        this.id = id;
        this.proCod = proCod;
        this.usuCod = usuCod;
        this.sucCod = sucCod;
    }
    public PlanMateria(PlanMateriaId id, int proCod, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Boolean sabados, Date plaMatIni, Date plaMatFin, String plaMatBim, Integer plaMatHpe, int usuCod, int sucCod) {
       this.id = id;
       this.proCod = proCod;
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.sabados = sabados;
       this.plaMatIni = plaMatIni;
       this.plaMatFin = plaMatFin;
       this.plaMatBim = plaMatBim;
       this.plaMatHpe = plaMatHpe;
       this.usuCod = usuCod;
       this.sucCod = sucCod;
    }
   
    public PlanMateriaId getId() {
        return this.id;
    }
    
    public void setId(PlanMateriaId id) {
        this.id = id;
    }
    public int getProCod() {
        return this.proCod;
    }
    
    public void setProCod(int proCod) {
        this.proCod = proCod;
    }
    public Boolean getLunes() {
        return this.lunes;
    }
    
    public void setLunes(Boolean lunes) {
        this.lunes = lunes;
    }
    public Boolean getMartes() {
        return this.martes;
    }
    
    public void setMartes(Boolean martes) {
        this.martes = martes;
    }
    public Boolean getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(Boolean miercoles) {
        this.miercoles = miercoles;
    }
    public Boolean getJueves() {
        return this.jueves;
    }
    
    public void setJueves(Boolean jueves) {
        this.jueves = jueves;
    }
    public Boolean getViernes() {
        return this.viernes;
    }
    
    public void setViernes(Boolean viernes) {
        this.viernes = viernes;
    }
    public Boolean getSabados() {
        return this.sabados;
    }
    
    public void setSabados(Boolean sabados) {
        this.sabados = sabados;
    }
    public Date getPlaMatIni() {
        return this.plaMatIni;
    }
    
    public void setPlaMatIni(Date plaMatIni) {
        this.plaMatIni = plaMatIni;
    }
    public Date getPlaMatFin() {
        return this.plaMatFin;
    }
    
    public void setPlaMatFin(Date plaMatFin) {
        this.plaMatFin = plaMatFin;
    }
    public String getPlaMatBim() {
        return this.plaMatBim;
    }
    
    public void setPlaMatBim(String plaMatBim) {
        this.plaMatBim = plaMatBim;
    }
    public Integer getPlaMatHpe() {
        return this.plaMatHpe;
    }
    
    public void setPlaMatHpe(Integer plaMatHpe) {
        this.plaMatHpe = plaMatHpe;
    }
    public int getUsuCod() {
        return this.usuCod;
    }
    
    public void setUsuCod(int usuCod) {
        this.usuCod = usuCod;
    }
    public int getSucCod() {
        return this.sucCod;
    }
    
    public void setSucCod(int sucCod) {
        this.sucCod = sucCod;
    }




}


