package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * PlanillaAsistenciaId generated by hbm2java
 */
public class PlanillaAsistenciaId  implements java.io.Serializable {


     private int plaCod;
     private int plaMat;
     private int matCod;

    public PlanillaAsistenciaId() {
    }

    public PlanillaAsistenciaId(int plaCod, int plaMat, int matCod) {
       this.plaCod = plaCod;
       this.plaMat = plaMat;
       this.matCod = matCod;
    }
   
    public int getPlaCod() {
        return this.plaCod;
    }
    
    public void setPlaCod(int plaCod) {
        this.plaCod = plaCod;
    }
    public int getPlaMat() {
        return this.plaMat;
    }
    
    public void setPlaMat(int plaMat) {
        this.plaMat = plaMat;
    }
    public int getMatCod() {
        return this.matCod;
    }
    
    public void setMatCod(int matCod) {
        this.matCod = matCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanillaAsistenciaId) ) return false;
		 PlanillaAsistenciaId castOther = ( PlanillaAsistenciaId ) other; 
         
		 return (this.getPlaCod()==castOther.getPlaCod())
 && (this.getPlaMat()==castOther.getPlaMat())
 && (this.getMatCod()==castOther.getMatCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlaCod();
         result = 37 * result + this.getPlaMat();
         result = 37 * result + this.getMatCod();
         return result;
   }   


}


