package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * PlanCursoId generated by hbm2java
 */
public class PlanCursoId  implements java.io.Serializable {


     private int plaCod;
     private int malCod;
     private int carCod;

    public PlanCursoId() {
    }

    public PlanCursoId(int plaCod, int malCod, int carCod) {
       this.plaCod = plaCod;
       this.malCod = malCod;
       this.carCod = carCod;
    }
   
    public int getPlaCod() {
        return this.plaCod;
    }
    
    public void setPlaCod(int plaCod) {
        this.plaCod = plaCod;
    }
    public int getMalCod() {
        return this.malCod;
    }
    
    public void setMalCod(int malCod) {
        this.malCod = malCod;
    }
    public int getCarCod() {
        return this.carCod;
    }
    
    public void setCarCod(int carCod) {
        this.carCod = carCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanCursoId) ) return false;
		 PlanCursoId castOther = ( PlanCursoId ) other; 
         
		 return (this.getPlaCod()==castOther.getPlaCod())
 && (this.getMalCod()==castOther.getMalCod())
 && (this.getCarCod()==castOther.getCarCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlaCod();
         result = 37 * result + this.getMalCod();
         result = 37 * result + this.getCarCod();
         return result;
   }   


}


