package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * PreDet generated by hbm2java
 */
public class PreDet  implements java.io.Serializable {


     private PreDetId id;

    public PreDet() {
    }

    public PreDet(PreDetId id) {
       this.id = id;
    }
   
    public PreDetId getId() {
        return this.id;
    }
    
    public void setId(PreDetId id) {
        this.id = id;
    }




}


