package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer preCod;
     private Date preFec;
     private Date preCarg;
     private Date preFecIni;
     private Date preFecFin;
     private Character preEstado;
     private int perCod;

    public Prestamo() {
    }

	
    public Prestamo(int perCod) {
        this.perCod = perCod;
    }
    public Prestamo(Date preFec, Date preCarg, Date preFecIni, Date preFecFin, Character preEstado, int perCod) {
       this.preFec = preFec;
       this.preCarg = preCarg;
       this.preFecIni = preFecIni;
       this.preFecFin = preFecFin;
       this.preEstado = preEstado;
       this.perCod = perCod;
    }
   
    public Integer getPreCod() {
        return this.preCod;
    }
    
    public void setPreCod(Integer preCod) {
        this.preCod = preCod;
    }
    public Date getPreFec() {
        return this.preFec;
    }
    
    public void setPreFec(Date preFec) {
        this.preFec = preFec;
    }
    public Date getPreCarg() {
        return this.preCarg;
    }
    
    public void setPreCarg(Date preCarg) {
        this.preCarg = preCarg;
    }
    public Date getPreFecIni() {
        return this.preFecIni;
    }
    
    public void setPreFecIni(Date preFecIni) {
        this.preFecIni = preFecIni;
    }
    public Date getPreFecFin() {
        return this.preFecFin;
    }
    
    public void setPreFecFin(Date preFecFin) {
        this.preFecFin = preFecFin;
    }
    public Character getPreEstado() {
        return this.preEstado;
    }
    
    public void setPreEstado(Character preEstado) {
        this.preEstado = preEstado;
    }
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }




}


