package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Profesion generated by hbm2java
 */
public class Profesion  implements java.io.Serializable {


     private Integer profCod;
     private String profDesc;

    public Profesion() {
    }

    public Profesion(String profDesc) {
       this.profDesc = profDesc;
    }
   
    public Integer getProfCod() {
        return this.profCod;
    }
    
    public void setProfCod(Integer profCod) {
        this.profCod = profCod;
    }
    public String getProfDesc() {
        return this.profDesc;
    }
    
    public void setProfDesc(String profDesc) {
        this.profDesc = profDesc;
    }




}


