package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer proCod;
     private Date proCarg;
     private Date proFecIni;
     private Date proFecFin;
     private Character proEstado;
     private String obs;
     private int perCod;

    public Profesor() {
    }

	
    public Profesor(int perCod) {
        this.perCod = perCod;
    }
    public Profesor(Date proCarg, Date proFecIni, Date proFecFin, Character proEstado, String obs, int perCod) {
       this.proCarg = proCarg;
       this.proFecIni = proFecIni;
       this.proFecFin = proFecFin;
       this.proEstado = proEstado;
       this.obs = obs;
       this.perCod = perCod;
    }
   
    public Integer getProCod() {
        return this.proCod;
    }
    
    public void setProCod(Integer proCod) {
        this.proCod = proCod;
    }
    public Date getProCarg() {
        return this.proCarg;
    }
    
    public void setProCarg(Date proCarg) {
        this.proCarg = proCarg;
    }
    public Date getProFecIni() {
        return this.proFecIni;
    }
    
    public void setProFecIni(Date proFecIni) {
        this.proFecIni = proFecIni;
    }
    public Date getProFecFin() {
        return this.proFecFin;
    }
    
    public void setProFecFin(Date proFecFin) {
        this.proFecFin = proFecFin;
    }
    public Character getProEstado() {
        return this.proEstado;
    }
    
    public void setProEstado(Character proEstado) {
        this.proEstado = proEstado;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public int getPerCod() {
        return this.perCod;
    }
    
    public void setPerCod(int perCod) {
        this.perCod = perCod;
    }




}


