package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int proCod;
     private String proDesc;
     private int tppCod;
     private String proTpd;
     private String proNro;
     private String proTel;
     private String proCel;
     private String proDir;
     private String proEma;

    public Proveedor() {
    }

	
    public Proveedor(int proCod, int tppCod) {
        this.proCod = proCod;
        this.tppCod = tppCod;
    }
    public Proveedor(int proCod, String proDesc, int tppCod, String proTpd, String proNro, String proTel, String proCel, String proDir, String proEma) {
       this.proCod = proCod;
       this.proDesc = proDesc;
       this.tppCod = tppCod;
       this.proTpd = proTpd;
       this.proNro = proNro;
       this.proTel = proTel;
       this.proCel = proCel;
       this.proDir = proDir;
       this.proEma = proEma;
    }
   
    public int getProCod() {
        return this.proCod;
    }
    
    public void setProCod(int proCod) {
        this.proCod = proCod;
    }
    public String getProDesc() {
        return this.proDesc;
    }
    
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc;
    }
    public int getTppCod() {
        return this.tppCod;
    }
    
    public void setTppCod(int tppCod) {
        this.tppCod = tppCod;
    }
    public String getProTpd() {
        return this.proTpd;
    }
    
    public void setProTpd(String proTpd) {
        this.proTpd = proTpd;
    }
    public String getProNro() {
        return this.proNro;
    }
    
    public void setProNro(String proNro) {
        this.proNro = proNro;
    }
    public String getProTel() {
        return this.proTel;
    }
    
    public void setProTel(String proTel) {
        this.proTel = proTel;
    }
    public String getProCel() {
        return this.proCel;
    }
    
    public void setProCel(String proCel) {
        this.proCel = proCel;
    }
    public String getProDir() {
        return this.proDir;
    }
    
    public void setProDir(String proDir) {
        this.proDir = proDir;
    }
    public String getProEma() {
        return this.proEma;
    }
    
    public void setProEma(String proEma) {
        this.proEma = proEma;
    }




}


