package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Recomendacion generated by hbm2java
 */
public class Recomendacion  implements java.io.Serializable {


     private int insCod;
     private Boolean recCert;
     private Boolean recCulminoEdl;
     private Boolean recEsLider;
     private Boolean recBautismo;
     private Boolean recEs;
     private Boolean recRecom;
     private String recActRea;
     private String recObs;
     private Boolean recEncFirma;
     private String recEncTel;
     private String recEncEmail;
     private Character recEstado;
     private int orgCod;
     private int volCod;

    public Recomendacion() {
    }

	
    public Recomendacion(int insCod, int orgCod, int volCod) {
        this.insCod = insCod;
        this.orgCod = orgCod;
        this.volCod = volCod;
    }
    public Recomendacion(int insCod, Boolean recCert, Boolean recCulminoEdl, Boolean recEsLider, Boolean recBautismo, Boolean recEs, Boolean recRecom, String recActRea, String recObs, Boolean recEncFirma, String recEncTel, String recEncEmail, Character recEstado, int orgCod, int volCod) {
       this.insCod = insCod;
       this.recCert = recCert;
       this.recCulminoEdl = recCulminoEdl;
       this.recEsLider = recEsLider;
       this.recBautismo = recBautismo;
       this.recEs = recEs;
       this.recRecom = recRecom;
       this.recActRea = recActRea;
       this.recObs = recObs;
       this.recEncFirma = recEncFirma;
       this.recEncTel = recEncTel;
       this.recEncEmail = recEncEmail;
       this.recEstado = recEstado;
       this.orgCod = orgCod;
       this.volCod = volCod;
    }
   
    public int getInsCod() {
        return this.insCod;
    }
    
    public void setInsCod(int insCod) {
        this.insCod = insCod;
    }
    public Boolean getRecCert() {
        return this.recCert;
    }
    
    public void setRecCert(Boolean recCert) {
        this.recCert = recCert;
    }
    public Boolean getRecCulminoEdl() {
        return this.recCulminoEdl;
    }
    
    public void setRecCulminoEdl(Boolean recCulminoEdl) {
        this.recCulminoEdl = recCulminoEdl;
    }
    public Boolean getRecEsLider() {
        return this.recEsLider;
    }
    
    public void setRecEsLider(Boolean recEsLider) {
        this.recEsLider = recEsLider;
    }
    public Boolean getRecBautismo() {
        return this.recBautismo;
    }
    
    public void setRecBautismo(Boolean recBautismo) {
        this.recBautismo = recBautismo;
    }
    public Boolean getRecEs() {
        return this.recEs;
    }
    
    public void setRecEs(Boolean recEs) {
        this.recEs = recEs;
    }
    public Boolean getRecRecom() {
        return this.recRecom;
    }
    
    public void setRecRecom(Boolean recRecom) {
        this.recRecom = recRecom;
    }
    public String getRecActRea() {
        return this.recActRea;
    }
    
    public void setRecActRea(String recActRea) {
        this.recActRea = recActRea;
    }
    public String getRecObs() {
        return this.recObs;
    }
    
    public void setRecObs(String recObs) {
        this.recObs = recObs;
    }
    public Boolean getRecEncFirma() {
        return this.recEncFirma;
    }
    
    public void setRecEncFirma(Boolean recEncFirma) {
        this.recEncFirma = recEncFirma;
    }
    public String getRecEncTel() {
        return this.recEncTel;
    }
    
    public void setRecEncTel(String recEncTel) {
        this.recEncTel = recEncTel;
    }
    public String getRecEncEmail() {
        return this.recEncEmail;
    }
    
    public void setRecEncEmail(String recEncEmail) {
        this.recEncEmail = recEncEmail;
    }
    public Character getRecEstado() {
        return this.recEstado;
    }
    
    public void setRecEstado(Character recEstado) {
        this.recEstado = recEstado;
    }
    public int getOrgCod() {
        return this.orgCod;
    }
    
    public void setOrgCod(int orgCod) {
        this.orgCod = orgCod;
    }
    public int getVolCod() {
        return this.volCod;
    }
    
    public void setVolCod(int volCod) {
        this.volCod = volCod;
    }




}


