package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Stand generated by hbm2java
 */
public class Stand  implements java.io.Serializable {


     private int staCod;
     private String staDesc;

    public Stand() {
    }

	
    public Stand(int staCod) {
        this.staCod = staCod;
    }
    public Stand(int staCod, String staDesc) {
       this.staCod = staCod;
       this.staDesc = staDesc;
    }
   
    public int getStaCod() {
        return this.staCod;
    }
    
    public void setStaCod(int staCod) {
        this.staCod = staCod;
    }
    public String getStaDesc() {
        return this.staDesc;
    }
    
    public void setStaDesc(String staDesc) {
        this.staDesc = staDesc;
    }




}


