package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * StockId generated by hbm2java
 */
public class StockId  implements java.io.Serializable {


     private int artCod;
     private int depCod;

    public StockId() {
    }

    public StockId(int artCod, int depCod) {
       this.artCod = artCod;
       this.depCod = depCod;
    }
   
    public int getArtCod() {
        return this.artCod;
    }
    
    public void setArtCod(int artCod) {
        this.artCod = artCod;
    }
    public int getDepCod() {
        return this.depCod;
    }
    
    public void setDepCod(int depCod) {
        this.depCod = depCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StockId) ) return false;
		 StockId castOther = ( StockId ) other; 
         
		 return (this.getArtCod()==castOther.getArtCod())
 && (this.getDepCod()==castOther.getDepCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getArtCod();
         result = 37 * result + this.getDepCod();
         return result;
   }   


}


