package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private StockId id;
     private Integer canTot;
     private Integer canMin;
     private Integer canMax;
     private int staCod;

    public Stock() {
    }

	
    public Stock(StockId id, int staCod) {
        this.id = id;
        this.staCod = staCod;
    }
    public Stock(StockId id, Integer canTot, Integer canMin, Integer canMax, int staCod) {
       this.id = id;
       this.canTot = canTot;
       this.canMin = canMin;
       this.canMax = canMax;
       this.staCod = staCod;
    }
   
    public StockId getId() {
        return this.id;
    }
    
    public void setId(StockId id) {
        this.id = id;
    }
    public Integer getCanTot() {
        return this.canTot;
    }
    
    public void setCanTot(Integer canTot) {
        this.canTot = canTot;
    }
    public Integer getCanMin() {
        return this.canMin;
    }
    
    public void setCanMin(Integer canMin) {
        this.canMin = canMin;
    }
    public Integer getCanMax() {
        return this.canMax;
    }
    
    public void setCanMax(Integer canMax) {
        this.canMax = canMax;
    }
    public int getStaCod() {
        return this.staCod;
    }
    
    public void setStaCod(int staCod) {
        this.staCod = staCod;
    }




}


