package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer sucCod;
     private String sucNombre;
     private String sucRuc;
     private String callePrincipal;
     private String nro;
     private String calleSecundaria;
     private String sucTelefono;
     private String sucCelular;
     private String sucEmail;
     private Date fechaHoraCarga;
     private int empCod;

    public Sucursal() {
    }

	
    public Sucursal(int empCod) {
        this.empCod = empCod;
    }
    public Sucursal(String sucNombre, String sucRuc, String callePrincipal, String nro, String calleSecundaria, String sucTelefono, String sucCelular, String sucEmail, Date fechaHoraCarga, int empCod) {
       this.sucNombre = sucNombre;
       this.sucRuc = sucRuc;
       this.callePrincipal = callePrincipal;
       this.nro = nro;
       this.calleSecundaria = calleSecundaria;
       this.sucTelefono = sucTelefono;
       this.sucCelular = sucCelular;
       this.sucEmail = sucEmail;
       this.fechaHoraCarga = fechaHoraCarga;
       this.empCod = empCod;
    }
   
    public Integer getSucCod() {
        return this.sucCod;
    }
    
    public void setSucCod(Integer sucCod) {
        this.sucCod = sucCod;
    }
    public String getSucNombre() {
        return this.sucNombre;
    }
    
    public void setSucNombre(String sucNombre) {
        this.sucNombre = sucNombre;
    }
    public String getSucRuc() {
        return this.sucRuc;
    }
    
    public void setSucRuc(String sucRuc) {
        this.sucRuc = sucRuc;
    }
    public String getCallePrincipal() {
        return this.callePrincipal;
    }
    
    public void setCallePrincipal(String callePrincipal) {
        this.callePrincipal = callePrincipal;
    }
    public String getNro() {
        return this.nro;
    }
    
    public void setNro(String nro) {
        this.nro = nro;
    }
    public String getCalleSecundaria() {
        return this.calleSecundaria;
    }
    
    public void setCalleSecundaria(String calleSecundaria) {
        this.calleSecundaria = calleSecundaria;
    }
    public String getSucTelefono() {
        return this.sucTelefono;
    }
    
    public void setSucTelefono(String sucTelefono) {
        this.sucTelefono = sucTelefono;
    }
    public String getSucCelular() {
        return this.sucCelular;
    }
    
    public void setSucCelular(String sucCelular) {
        this.sucCelular = sucCelular;
    }
    public String getSucEmail() {
        return this.sucEmail;
    }
    
    public void setSucEmail(String sucEmail) {
        this.sucEmail = sucEmail;
    }
    public Date getFechaHoraCarga() {
        return this.fechaHoraCarga;
    }
    
    public void setFechaHoraCarga(Date fechaHoraCarga) {
        this.fechaHoraCarga = fechaHoraCarga;
    }
    public int getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(int empCod) {
        this.empCod = empCod;
    }




}


