package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * TarjetaCobroId generated by hbm2java
 */
public class TarjetaCobroId  implements java.io.Serializable {


     private int tarCod;
     private int cobCod;

    public TarjetaCobroId() {
    }

    public TarjetaCobroId(int tarCod, int cobCod) {
       this.tarCod = tarCod;
       this.cobCod = cobCod;
    }
   
    public int getTarCod() {
        return this.tarCod;
    }
    
    public void setTarCod(int tarCod) {
        this.tarCod = tarCod;
    }
    public int getCobCod() {
        return this.cobCod;
    }
    
    public void setCobCod(int cobCod) {
        this.cobCod = cobCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TarjetaCobroId) ) return false;
		 TarjetaCobroId castOther = ( TarjetaCobroId ) other; 
         
		 return (this.getTarCod()==castOther.getTarCod())
 && (this.getCobCod()==castOther.getCobCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTarCod();
         result = 37 * result + this.getCobCod();
         return result;
   }   


}


