package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * TarjetaCobro generated by hbm2java
 */
public class TarjetaCobro  implements java.io.Serializable {


     private TarjetaCobroId id;

    public TarjetaCobro() {
    }

    public TarjetaCobro(TarjetaCobroId id) {
       this.id = id;
    }
   
    public TarjetaCobroId getId() {
        return this.id;
    }
    
    public void setId(TarjetaCobroId id) {
        this.id = id;
    }




}


