package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer tarCod;
     private String tarDesc;
     private int entCod;

    public Tarjeta() {
    }

	
    public Tarjeta(int entCod) {
        this.entCod = entCod;
    }
    public Tarjeta(String tarDesc, int entCod) {
       this.tarDesc = tarDesc;
       this.entCod = entCod;
    }
   
    public Integer getTarCod() {
        return this.tarCod;
    }
    
    public void setTarCod(Integer tarCod) {
        this.tarCod = tarCod;
    }
    public String getTarDesc() {
        return this.tarDesc;
    }
    
    public void setTarDesc(String tarDesc) {
        this.tarDesc = tarDesc;
    }
    public int getEntCod() {
        return this.entCod;
    }
    
    public void setEntCod(int entCod) {
        this.entCod = entCod;
    }




}


