package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Tematico generated by hbm2java
 */
public class Tematico  implements java.io.Serializable {


     private Integer temCod;
     private String temDesc;

    public Tematico() {
    }

    public Tematico(String temDesc) {
       this.temDesc = temDesc;
    }
   
    public Integer getTemCod() {
        return this.temCod;
    }
    
    public void setTemCod(Integer temCod) {
        this.temCod = temCod;
    }
    public String getTemDesc() {
        return this.temDesc;
    }
    
    public void setTemDesc(String temDesc) {
        this.temDesc = temDesc;
    }




}


