package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Titular generated by hbm2java
 */
public class Titular  implements java.io.Serializable {


     private Integer titCod;
     private String titNom;
     private String titDirec;
     private String titTel;

    public Titular() {
    }

    public Titular(String titNom, String titDirec, String titTel) {
       this.titNom = titNom;
       this.titDirec = titDirec;
       this.titTel = titTel;
    }
   
    public Integer getTitCod() {
        return this.titCod;
    }
    
    public void setTitCod(Integer titCod) {
        this.titCod = titCod;
    }
    public String getTitNom() {
        return this.titNom;
    }
    
    public void setTitNom(String titNom) {
        this.titNom = titNom;
    }
    public String getTitDirec() {
        return this.titDirec;
    }
    
    public void setTitDirec(String titDirec) {
        this.titDirec = titDirec;
    }
    public String getTitTel() {
        return this.titTel;
    }
    
    public void setTitTel(String titTel) {
        this.titTel = titTel;
    }




}


