package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Titulo generated by hbm2java
 */
public class Titulo  implements java.io.Serializable {


     private Integer titCod;
     private String titDesc;

    public Titulo() {
    }

    public Titulo(String titDesc) {
       this.titDesc = titDesc;
    }
   
    public Integer getTitCod() {
        return this.titCod;
    }
    
    public void setTitCod(Integer titCod) {
        this.titCod = titCod;
    }
    public String getTitDesc() {
        return this.titDesc;
    }
    
    public void setTitDesc(String titDesc) {
        this.titDesc = titDesc;
    }




}


