package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * TpAdq generated by hbm2java
 */
public class TpAdq  implements java.io.Serializable {


     private Integer tpadqCod;
     private String tpadqDesc;

    public TpAdq() {
    }

    public TpAdq(String tpadqDesc) {
       this.tpadqDesc = tpadqDesc;
    }
   
    public Integer getTpadqCod() {
        return this.tpadqCod;
    }
    
    public void setTpadqCod(Integer tpadqCod) {
        this.tpadqCod = tpadqCod;
    }
    public String getTpadqDesc() {
        return this.tpadqDesc;
    }
    
    public void setTpadqDesc(String tpadqDesc) {
        this.tpadqDesc = tpadqDesc;
    }




}


