package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * TpArt generated by hbm2java
 */
public class TpArt  implements java.io.Serializable {


     private Integer tpartCod;
     private String tpartDesc;

    public TpArt() {
    }

    public TpArt(String tpartDesc) {
       this.tpartDesc = tpartDesc;
    }
   
    public Integer getTpartCod() {
        return this.tpartCod;
    }
    
    public void setTpartCod(Integer tpartCod) {
        this.tpartCod = tpartCod;
    }
    public String getTpartDesc() {
        return this.tpartDesc;
    }
    
    public void setTpartDesc(String tpartDesc) {
        this.tpartDesc = tpartDesc;
    }




}


