package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Tpprov generated by hbm2java
 */
public class Tpprov  implements java.io.Serializable {


     private Integer tppCod;
     private String tppDesc;

    public Tpprov() {
    }

    public Tpprov(String tppDesc) {
       this.tppDesc = tppDesc;
    }
   
    public Integer getTppCod() {
        return this.tppCod;
    }
    
    public void setTppCod(Integer tppCod) {
        this.tppCod = tppCod;
    }
    public String getTppDesc() {
        return this.tppDesc;
    }
    
    public void setTppDesc(String tppDesc) {
        this.tppDesc = tppDesc;
    }




}


