package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Unidad generated by hbm2java
 */
public class Unidad  implements java.io.Serializable {


     private Integer uniCod;
     private String uniDesc;

    public Unidad() {
    }

    public Unidad(String uniDesc) {
       this.uniDesc = uniDesc;
    }
   
    public Integer getUniCod() {
        return this.uniCod;
    }
    
    public void setUniCod(Integer uniCod) {
        this.uniCod = uniCod;
    }
    public String getUniDesc() {
        return this.uniDesc;
    }
    
    public void setUniDesc(String uniDesc) {
        this.uniDesc = uniDesc;
    }




}


