package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private String usuario;
     private String email;
     private String password;
     private Date createTime;

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, String usuario, String password) {
        this.id = id;
        this.usuario = usuario;
        this.password = password;
    }
    public Usuario(UsuarioId id, String usuario, String email, String password, Date createTime) {
       this.id = id;
       this.usuario = usuario;
       this.email = email;
       this.password = password;
       this.createTime = createTime;
    }
   
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


