package its.model;
// Generated 06/03/2017 11:36:42 PM by Hibernate Tools 4.3.1



/**
 * Voluntariado generated by hbm2java
 */
public class Voluntariado  implements java.io.Serializable {


     private Integer volCod;
     private String volDesc;

    public Voluntariado() {
    }

    public Voluntariado(String volDesc) {
       this.volDesc = volDesc;
    }
   
    public Integer getVolCod() {
        return this.volCod;
    }
    
    public void setVolCod(Integer volCod) {
        this.volCod = volCod;
    }
    public String getVolDesc() {
        return this.volDesc;
    }
    
    public void setVolDesc(String volDesc) {
        this.volDesc = volDesc;
    }




}


